# Generated by Django 6.0.3 on 2026-06-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_report_reporter_report_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Fasilitas Umum', 'Fasilitas Umum'), ('infra', 'Infrastruktur'), ('kebersihan', 'Kebersihan'), ('lingkungan', 'Lingkungan'), ('keamanan', 'Keamanan'), ('transportasi', 'Transportasi'), ('Infrastruktur', 'Infrastruktur'), ('Kebersihan', 'Kebersihan'), ('Lingkungan', 'Lingkungan'), ('Keamanan', 'Keamanan'), ('Transportasi', 'Transportasi')], max_length=100),
        ),
    ]
